# Generated by Django 4.0.2 on 2022-02-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summa',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
