# Generated by Django 4.0.2 on 2022-02-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='ost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
