# Generated by Django 4.0.2 on 2022-02-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_datas_ost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='data1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
